package sw19.moring03.paint.utils;

public enum Tool {
    DRAW_POINT, DRAW_LINE, FILL, ERASER, DRAW_CIRCLE, DRAW_RECTANGLE, DRAW_PATH, DRAW_OVAL, TAKE_PHOTO,
    DRAW_TEXT, SPRAY_CAN, DRAW_TRIANGLE, DRAW_STAR, DRAW_TREE, DRAW_HEART;
}